### ISSUE TITLE
Adding support for grepping for packages

### ISSUE THREAD

**Issue by silentboatman** [shellkr/pachist#7]
There's a bug in `empathy` that I have to patch everytime there's an update. Recently `empathy` started to act weird and I suspected that `pacman -Su` had updated it without me noticing it. So, I did a `pachist 20000 | grep empathy` and yes, there was an update I had missed.

Anyhow, it would be great if pachist had the ability to filer/grep one or several packages. Something like this:

proposed syntax | corresponding commands
----------------------|---------------------------------
pachist empathy | pachist 20000 \| grep empathy
pachist empathy 20 | pachist 20000 \| grep empathy \| tail 20
pachist -v empathy | pachist 20000 \| grep empathy (+ empathy output)
pachist empathy pidgin | pachist 20000 \| grep -E 'empathy\|pidgin'

**Comment by Almehdi** [comment]
Yes, this sounds like an interesting feature. We would need something like ```$(command -v $1)``` to safeguard and make sure if it is an installed application and if not give an understandable error. Not using a flag for this might even be better.

**Comment by silentboatman** [comment]
Has been implemented: cddec6196184107a853e2b9023af7d9d6ac5f562
